favicon: "https://cdn.jsdelivr.net/gh/mazixiang/assets@master/icon/main_icon.ico"

index:
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text: 'Keep it simple, stupid.'  # 为空则按 hexo config.subtitle 显示

about:
  introduce: DJMAX Respect V / 明日方舟 / Terraria # 支持 HTML
  avatar: "https://cdn.jsdelivr.net/gh/mazixiang/assets@master/picgo/20200525222232.jpg"
  name: mazixiang
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/mazixiang' }
    - { class: 'iconfont icon-mail', link: 'mailto:mazixiang2012@gmail.com' }
    - { class: 'iconfont icon-steam', link: 'https://steamcommunity.com/id/thehunchn/' }

navbar:
  blog_title: mazixiang

post:
  copyright:  # 版权声明
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" rel="nofollow noopener">CC BY-SA 3.0 协议</a> 。转载请注明出处！<br>如有错误或侵权，请<a href="mailto:mazixiang2012@gmail.com"><strong>点击这里，给我发邮件</strong></a>，我会马上修改或删除！'
<<<<<<< HEAD
=======
  updated:  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
    enable: true
    content: 本文最后更新于：  # 描述文字
    relative: true  # 是否使用相对时间表示，比如："3 天前"
>>>>>>> a6522d83fc105955a3776e59e51163b2d244343d
  prev_next:  # 文章底部上一篇下一篇功能
    enable: false
  toc:  # 文章右侧目录
    enable: true
    headingSelector: h2,h3,h4,h5,h6
    collapseDepth: 0  # 层级的折叠深度，0 是全部折叠，6 是全部不折叠
